# .travis.yml file for pybooru

os:
    - linux

language: python

# Python version
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

branches:
    - develop
    - master

install:
    # Install requests
    - pip install requests

    # Install pylint
    - sudo apt-get install pylint

before_script:
    # Remove python binari files
    - rm --recursive --force --verbose *.py[cod]
    # Run pylint
    - pylint --errors-only --rcfile=.pylintrc pybooru/

script:
    # Run test script, but at the moment is a provisional test
    - python provisional_test.py
