# 2014-10-11 13:10 by LuqueDaniel .travis.yml for Travis CI

language: python

# Python version
python:
    - "2.6"
    - "2.7"

branches:
    - develop
    - master

install:
    # Install requests
    - pip install requests

before_script:
    # Remove python binari files
    - rm --recursive --force --verbose *.py[cod]

# Run test script, but at the moment is a provisional test
script: python provisional_test.py
