# .travis.yml file for pybooru

# Python version
matrix:
  include:
    - python: '2.7'
      os: linux
      language: python

    - python: '3.3'
      os: linux
      language: python

    - python: '3.4'
      os: linux
      language: python

    - python: '3.5'
      os: linux
      language: python

    - python: '3.6'
      os: linux
      language: python

    # OSX ENV
    - os: osx
      env: PYTHON_VERSION=3.6
      language: generic

branches:
    - develop
    - master

install:
    # Install requests
    - pip install -r requirements.txt

    # Install flake8
    - pip install flake8

before_script:
    # Run pylint
    - flake8 pybooru/

script:
    # Run test script, but at the moment is a provisional test
    - python provisional_test.py
