# .travis.yml file for pybooru

# Python version
matrix:
  include:
    - python: '2.7'
      os: linux
      language: python

    - python: '3.3'
      os: linux
      language: python

    - python: '3.4'
      os: linux
      language: python

    - python: '3.5'
      os: linux
      language: python

    - python: '3.6'
      os: linux
      language: python

    # OSX ENV
    - os: osx
      env: PYTHON_VERSION=2.7
      language: generic

    - os: osx
      env: PYTHON_VERSION=3.6
      language: generic

branches:
    - develop
    - master

install:
    # Install requests
    - |
      if ["$TRAVIS_OS_NAME" == "osx"]; then
        if ["$PYTHON_VERSION" == "2.7"]; then
          pip2 install -r requirements.txt;
        else
          pip3 install -r requirements.txt;
        fi
      fi

    # Install flake8
    - pip install flake8

before_script:
    # Run pylint
    - flake8 pybooru/

script:
    # Run test script, but at the moment is a provisional test
    - python provisional_test.py
