# .travis.yml file for pybooru

# Python version
matrix:
  include:
    - python: '2.7'
      os: linux
      language: python

    - python: '3.3'
      os: linux
      language: python

    - python: '3.4'
      os: linux
      language: python

    - python: '3.5'
      os: linux
      language: python

    - python: '3.6'
      os: linux
      language: python

    # OSX ENV
    - os: osx
      env: PYTHON_VERSION=2.7
      language: generic

    - os: osx
      env: PYTHON_VERSION=3.6
      language: generic

branches:
    - develop
    - master

install:
    # Install requests and flake8
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        if [ "$PYTHON_VERSION" == "2.7" ]; then
          pip2 install -r requirements.txt;
          pip2 install flake8;
        else
          pip3 install -r requirements.txt;
          pip3 install flake8;
        fi
      else
        pip install -r requirements.txt;
        pip install flake8;
      fi

before_script:
    # Run pylint
    - flake8 pybooru/

script:
    # Run test script, but at the moment is a provisional test
    - python provisional_test.py
