# AppVeyor recipe

# Not a VS project
build: off

environment:
  matrix:
    # List: https://www.appveyor.com/docs/windows-images-software/#python
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.17"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.4"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.8"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.5"
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.0"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOMEDRIVE%%HOMEPATH%

install:
  - "%PYTHON%/Scripts/pip.exe install pipenv"
  - pipenv install --dev

test_script:
  - pipenv run pylint pybooru/
  # Run test script, but at the moment is a provisional test
  - pipenv run python provisional_test.py"
