# AppVeyor recipe

# Not a VS project
build: off

environment:
  matrix:
    # List: https://www.appveyor.com/docs/installed-software/#python
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOMEDRIVE%%HOMEPATH%

install:
  - pip install pipenv
  - pipenv install --dev

test_script:
  - pipenv run pylint pybooru/
  # Run test script, but at the moment is a provisional test
  - "%PYTHON%/python.exe provisional_test.py"
