environment:
  matix:
    # List: https://www.appveyor.com/docs/installed-software/#python
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

  init:
    - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOMEDRIVE%%HOMEPATH%

  install:
    # Remove binary
    - DEL /S .\*.pyc
    - RD /S /Q .\pybooru\__pycache__

    # Install reqeusts
    - pip install requests --user

    # Not a VS project
  build: off

  test_script:
  - python provisional_test.py
