# Conda environment configuration file (optional)
# you needs to install conda and execute the following command:
# conda env create -f environment.yml

name: pybooru

dependencies:
  - python=3.5
  - requests
  - sphinx
  - pylint
  - pip:
    - sphinx-rtd-theme
